### ISSUE TITLE
Unbiased DFA

### ISSUE THREAD

**Issue by genomewalker** [stfbnc/fathon#10]
Hi @stfbnc 
thank you very much for your package. It is super useful. I was wondering if fathon could include the unbiased DFA for short time series as is described [here](https://www.sciencedirect.com/science/article/abs/pii/S0378437118303637)

Many thanks
Antonio

**Comment by stfbnc** [comment]
Hi @genomewalker, thanks!
I'm quite busy at the moment, but I'll have a look at the paper and let you know.

**Comment by genomewalker** [comment]
@stfbnc Many thanks! 😀

**Comment by stfbnc** [comment]
Hi @genomewalker,

I've implemented a first version, but I'm having some trouble reproducing correct results.

In particular, I do not fully understand how $W_A^k$ and $W_B^k$ are defined in equation 12.

Let's say $s = 3$, so it should be $W_A^k = \\{Z^{Dk}(1), Z^{Dk}(2), Z^{Dk}(3)\\}$, $W_B^k = \\{Z^{Dk}(1), -Z^{Dk}(2), Z^{Dk}(3)\\}$. So, $m$ should the $m$ th element of $Z^{Dk}$, but I'm confused by $m$ being the same for consecutive elements of $W_A^k$ in equation 12. $W_A^k$ should also have $s$ elements, as the first sum in equation 13 goes over $s$ elements.

Is my understanding of equation 12 correct, or am I missing something?

**Comment by stfbnc** [comment]
Hi @genomewalker,

I managed to resolve, there is now a new version of the package (v1.3.2) that includes the unbiased DFA.

There is a new optional argument in the function [`fathon.DFA.computeFlucVec`](https://fathon.readthedocs.io/en/latest/fun_class/fathon.DFA.html#fathon.DFA.computeFlucVec), `unbiased`, that when set to True computes the unbiased version of the DFA as described in the paper.

**Comment by genomewalker** [comment]
That is excellent, @stfbnc! Thank you very much, and apologies for the radio sile; it has been a time of grant submissions :tired_face:  
That will be super useful :smiley:
