### ISSUE TITLE
Error in starting fathon

### ISSUE THREAD

**Issue by ddandreev2003** [stfbnc/fathon#13]
Hello! Thanks for your usefull library. I have a problem in import fathon.
Traceback (most recent call last):

  File ~\untitled9.py:8 in <module>
    import fathon

  File ~\AppData\Roaming\Python\Python39\site-packages\fathon\__init__.py:20 in <module>
    from .dfa import DFA

  File fathon\dfa.pyx:1 in init fathon.dfa

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

How can i fix it?

**Comment by stfbnc** [comment]
Hi @ddandreev2003, thanks!

Could you tell me the version of fathon and numpy you are using?

**Comment by ddandreev2003** [comment]
fathon 1.3.2 and numpy 1.21.5

**Comment by ddandreev2003** [comment]
Sorry, after updating all problems shut down. Thanks for your help

**Comment by stfbnc** [comment]
Thanks, I've updated the minimum numpy version in the README.

I've noticed now it was not updated when the latest fathon version was released (now is numpy >= 1.22)
