### ISSUE TITLE
When importing fathon into Jupyter Notebooks, I get the following error.

### ISSUE THREAD

**Issue by sabrasisler** [stfbnc/fathon#14]
ValueError                                Traceback (most recent call last)
[/Users/sabrasisler/Desktop/ActionLab/StandingPosture/dfa_analysis.ipynb](https://file+.vscode-resource.vscode-cdn.net/Users/sabrasisler/Desktop/ActionLab/StandingPosture/dfa_analysis.ipynb) Cell 1 in 1
----> 1 import fathon

File [/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fathon/__init__.py:20](https://file+.vscode-resource.vscode-cdn.net/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fathon/__init__.py:20)
     17 import platform
     18 import os
---> 20 from .dfa import DFA
     21 from .mfdfa import MFDFA
     22 from .dcca import DCCA

File fathon[/dfa.pyx:1](https://file+.vscode-resource.vscode-cdn.net/dfa.pyx:1), in init fathon.dfa()

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by stfbnc** [comment]
Hi, you should probably upgrade numpy to a more recent version.

**Comment by stfbnc** [comment]
Hi, I'm closing the issue, feel free to repoen it if the problem was not the numpy version.
