### ISSUE TITLE
f(alpha) > 1?

### ISSUE THREAD

**Issue by settwi** [stfbnc/fathon#15]
Hi there,

I was under the impression that when investigating multifractal spectra, f(alpha) should not rise above 1. Running the example notebook it looks like that f(alpha) > 1 for some (negative?) moments _q_.

I'm no expert on multifractal spectra, but I've been trying to apply the formalism using [WTMM](https://en.wikipedia.org/wiki/Wavelet_transform_modulus_maxima_method) to some solar flare X-ray data for a while, using a Python adaptation from this paper [2007ApJ...662..691M](https://ui.adsabs.harvard.edu/abs/2007ApJ...662..691M/abstract). Usually when spectra make odd shapes like that, they are either noisy, or the algorithm is busted.

Thoughts and/or references?
I can put my code up on a public GitHub too if that would be helpful.

Best
William

**Comment by settwi** [comment]
Pretty sure I had an issue with window widths.
If the windows don't cover a wide enough range the multifractal spectrum gets polluted.

Overall, this package is fast and works better than an implementation of WTMM I've been working on. Thank you!!!!!!

**Comment by stfbnc** [comment]
Hi William, sorry for the very late reply, these months I was very busy.

Glad to know the issue is resolved.

Just to know, did you also have a change in the concavity of the spectrum when f(alpha) > 1?

**Comment by settwi** [comment]
Yeah, it was concave up.

**Comment by settwi** [comment]
hey just a followup question about the MFDFA routines.
do you have a version that implement the Y(i) as in eq. 7 in [Kantelhardt+2002](https://arxiv.org/abs/physics/0202070)?
they note:

> However, the MF-DFA method can only determine positive generalized Hurst exponents h(q), and it already becomes inaccurate for strongly anti-correlated signals when h(q) is close to zero. In such cases, a modifed (MF-)DFA technique has to be used.


Might be a nice addition to add, and not too much more work. similar fluctuation function definition...
\- WS

**Comment by stfbnc** [comment]
Hi William,

I'll look into it.

The logarithmic summation for q = 0 is already implemented. Did you notice inconsistencies for q = 0?

**Comment by settwi** [comment]
I was getting nans when q = 0 and a divergent situation with q -> 0. i’ll double check today though. if i find a particular data set that causes issues i’ll send it your way!

**Comment by settwi** [comment]
Looks like I probably had an error somewhere else. q = 0 gives sensible results as far as I can tell.

**Comment by stfbnc** [comment]
ok thanks. I'm also noticing a divergence for q->0, I'm making some tests and will release a fix asap

**Comment by stfbnc** [comment]
Hi @settwi, there is a new version that solves the divergence for q->0

**Comment by settwi** [comment]
Thank you!
