### ISSUE TITLE
How to explain H>1 calculated by DFA and MFDFA

### ISSUE THREAD

**Issue by mmyyyzpl** [stfbnc/fathon#16]
I replaced the data for the example (DFA and MFDFA), but I found that the calculated H value was greater than 1. In theory, H should be at [0,1], but what does the test result H>1 mean

**Comment by stfbnc** [comment]
Hi, the Hurst exponent is defined in [0,1], but DFA (and MFDFA) computes a generalization of the Hurst exponent.

H > 1 means your time series is non stationary (like a fractional brownian motion)
