### ISSUE TITLE
Possible to have automated installation through pip or conda?

### ISSUE THREAD

**Issue by ali-ramadhan** [stfbnc/fathon#2]
I wonder if providing a Python package installable via `pip` or `conda` would make fathon more accessible and easier to install. I'm not super familiar with either but because of the C depdencies, presumably `conda` is the better option?

GSL seems to be a pre-requisite which is available through most Linux package managers. Installing fathon on Windows might prove difficult and it looks like you might need to install all of Cygwin just to get GSL to install fathon. I might mention this as most Windows users have no idea what Cygwin is.

I was not able to install fathon myself.

I believe the installation instructions are unfriendly. fathon seems much harder to install for me than the vast majority of Python packages, many of them which depend on C libraries too.

Besides having to manually install or compile GSL, you also need to know where include and library files are placed on your operating system, and you need to know the "standard location of Python packages" for your particular OS and Python environment combination.

I think this is a huge barrier to usability and most Python users won't be able to install fathon.

**Comment by stfbnc** [comment]
Ok, I'll try to make fathon available via `pip`, or at least include GSL directly in the package.

I've realized now that is not clear from the README, but for now the package is intended for macOS and Linux only. I do not have access to a Windows machine.

**Comment by stfbnc** [comment]
@ali-ramadhan I have modified the README.md with the new installation guidelines.
I did not manage to make fathon available via pip yet, but GSL is no more required now and is automatically installed along with fathon in the last of the paths where python searches when a package is imported.

Let me know if you still have problems with the installation.

**Comment by ashwinvis** [comment]
I agree with @ali-ramadhan on the GSL installation approach. Consider improving installation of GSL when available via system manager (for Linux: `apt`, `pacman`, `yum` etc.) and fallback to [conda](https://anaconda.org/conda-forge/gsl) for other platforms / when sudo rights are not available. I would prefer to do

     sudo apt install libgsl-dev

in Ubuntu. The current approach has an added problem that by moving GSL source files, the git repo is dirty after installation.

**Comment by stfbnc** [comment]
@ali-ramadhan @ashwinvis fathon is now available via `pip` and the user can choose to install GSL by themselves or let `pip` download and install it.
See the README.md for the installation guidelines.

**Comment by ashwinvis** [comment]
It would be nice if you can also `git tag ...` the commit corresponding to the PyPI release and push the tag to GitHub.

**Comment by stfbnc** [comment]
@ashwinvis  Done!

**Comment by ali-ramadhan** [comment]
@stfbnc Thanks for putting in the work to add fathon to pip!

I'm very sorry for my slow reply.

Currently installing fathon through pip.

It took like ~10 minutes until `setup.py` started running where it seemed like pip was stuck but `htop` showed some intermittent cc/gcc activity so I assumed things were compiling in the background. Was it perhaps compiling some fathon dependencies? If so, might be nice to print a message saying that so users don't think it's stuck or that there's a bug. Most pip packages install in seconds so I was surprised that it took much longer than that.

`setup.py` also took a while to run but there was a message so that was fine.

I thought GSL would be automatically installed but after `pip install fathon` it seemed it's not found:
```
>>> import fathon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/fathon/__init__.py", line 19, in <module>
    from .dfa import DFA
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
```

**Comment by ali-ramadhan** [comment]
I installed GSL through the Arch Linux package manager and looks like fathon works now!

**Comment by stfbnc** [comment]
> It took like ~10 minutes before setup.py started running where it seemed like pip was stuck but htop showed some intermittent cc/gcc activity so I assumed things were compiling in the background. Was it perhaps compiling some fathon dependencies?

It was installing GSL under `/usr/local`.

> I thought GSL would be automatically installed according to the README but after pip install fathon it seemed that it was not installed

Could you please check if GSL includes are under `/usr/local/include/gsl`, and if GSL libraries are under `/usr/local/lib`?

Could you also please check where the package managere installed GSL?

**Comment by ali-ramadhan** [comment]
Thanks for the quick reply!

Yes you were right, I think pip installed GSL in `/usr/local/` while pacman installed GSL in `/usr/`, not sure if this is an Arch Linux quirk.

**Comment by ashwinvis** [comment]
> I think pip installed GSL in `/usr/local/`...

This it the right thing to do for installations not done by system package manager. This avoids conflicts. An alternative would be the `/opt` directory.

**Comment by ali-ramadhan** [comment]
Ah I see, that's good to know. Maybe my local python wasn't looking in `/usr/local/`...

I uninstalled GSL using pacman and then was able to import fathon using the GSL it built with `LD_LIBRARY_PATH=/usr/local/lib`.
```
$ export LD_LIBRARY_PATH=/usr/local/lib
$ python
Python 3.7.4 (default, Oct  4 2019, 06:57:26) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fathon
>>>
```

**Comment by ashwinvis** [comment]
Yes, and this step is also pointed out in the readme. I think the issue can be closed for now.

I should note that one would have admin rights only on personal computers, @stfbnc.  One possible improvement for the future is to avoid `sudo ... ` steps and instead:

```bash
./configure --prefix=$HOME/.local
make
make install
```

**Comment by ali-ramadhan** [comment]
Ah you're right, sorry for not properly reading the note about setting `LD_LIBRARY_PATH`. It even had a big ⚠️ on it!
