### ISSUE TITLE
File locations in tests

### ISSUE THREAD

**Issue by ali-ramadhan** [stfbnc/fathon#3]
Since the text files live in the `test` directory should these lines be changed to, e.g. `ts1 = np.loadtxt('ts1.txt')`?

https://github.com/stfbnc/fathon/blob/ed981f6a84193557daffa35361420628c8f32b57/tests/test_fathon.py#L8-L12

**Comment by stfbnc** [comment]
A path like that is needed for automated tests, since TravisCI runs the script `test_fathon.py` from `.travis.yml`'s location.

**Comment by ali-ramadhan** [comment]
Ah sorry just saw the Travis CI badge on the README. Tests are passing there so I guess this is not an issue.
