### ISSUE TITLE
examples require updating

### ISSUE THREAD

**Issue by andrewcztrack** [stfbnc/fathon#7]
Hi @stfbnc @danielskatz 

Apologies but i think the examples require updating.
Best,
Andrew

**Comment by danielskatz** [comment]
@andrewcztrack - I'm not sure why you are telling me this.  While I made one commit to this package at the start of this year (https://github.com/stfbnc/fathon/commit/9593fe14bc055c434cc1dfc07142dc3879b03b09) as part of the process of publishing it in JOSS, I'm not an author of it.  I'm now going to stop watching this issue.

**Comment by stfbnc** [comment]
Hi @andrewcztrack, my apologies!
Examples are now updated.
