### ISSUE TITLE
pip3?

### ISSUE THREAD

**Issue by ferosas** [stfbnc/fathon#8]
Hi!
I just tried to install fathon via pip3 and got a "No matching distribution found for fathon". 
Is that to be expected?
Thanks in advance!
Fernando

**Comment by ferosas** [comment]
MacOS Catalina

**Comment by stfbnc** [comment]
And which python3 version? You can also try to upgrade pip3 to see if it works.

**Comment by ferosas** [comment]
Thanks. I'm using Python 3.9, and tried after updating pip3... but still getting the same error

**Comment by stfbnc** [comment]
Ok, the problem is there are no wheels on pypi for Python 3.9 yet. Tomorrow I will upload them, and let you know.
Thanks,
Stefano

**Comment by ferosas** [comment]
Wonderful, thank you!

**Comment by stfbnc** [comment]
@ferosas Python 3.9 wheels for macOS are now available.
Let me know if you still have problems.

Stefano

**Comment by ferosas** [comment]
It worked beautifully, many thanks Stefano!
Fernando
