### ISSUE TITLE
Issue in Plotting 1st graph

### ISSUE THREAD

**Issue by Rabia-Raja** [stfbnc/fathon#9]
Hy. Your code is amazing.
I am trying to implement MFDFA.py code for my data series. But the first graph of this file is plotting values from 3 to 7 on X-axis
i.e. ln(n). But I want to plot this graph against number of days i.e. 10- 1000 (according to my data). So, where I should make a change. Kindly guide

**Comment by stfbnc** [comment]
Hi, thank you!

Are you referring to the `mfdfa_example.py` file in the `examples` folder?
If so (and supposing `n` is your days 10-1000), you can do one of the following:

1. from line 25 to 38, substitute `np.log(n)` with `n`, but the points will not follow a linear trend anymore
2. after line 33, add this line: `plt.xticks(np.log(n), [str(x) for x in n])`

**Comment by Rabia-Raja** [comment]
Hi
Thanks a lot for your reply. I tried your suggestion but the obtained graph
does not seems accurate. I am attaching a figure, you can see it. I want to
make a graph like this. Also, I want to give different values of q like q
=1, 2 and 3 etc. So, which line of code I need to change in same MFDFA.py
file. is it Qs List?

**Comment by stfbnc** [comment]
Hi,
I cannot see the attachment, could you attach the figure dragging it into the text box?

For different q values yes, you can redefine the `qs` list with your preferred values.

**Comment by Rabia-Raja** [comment]
Sure, here it is.
[image: mfdfa.png]

**Comment by stfbnc** [comment]
Sorry, I still cannot see the figure. Probably you have to drag it directly from your computer to the github site.

**Comment by Rabia-Raja** [comment]
![mfdfa](https://user-images.githubusercontent.com/39183049/122209121-98a4a580-cebd-11eb-8b0d-54cd6c049d36.png)

**Comment by Rabia-Raja** [comment]
I have posted  graph here. can  you see it now?

**Comment by Rabia-Raja** [comment]
I posted figure on gitub issue. can you see it now?

**Comment by stfbnc** [comment]
Yes, I can see it, thanks.

You can simply substitute the x ticks labels (that are now referring to `ln(n)`) with `n`.
So if you have computed MFDFA for days 10-1000, and say that you want to see on the x axis the values for 10, 30, 100, 300, 1000 days, you can do something like that:

`n_vals = [10, 30, 100, 300, 1000]`
`plt.xticks([np.log(x) for x in n_vals], n_vals)`

Add those lines after line 33, substitute line 34 with `plt.xlabel('n (days)', fontsize=14)`, and it should work fine.

**Comment by Rabia-Raja** [comment]
Thankyou so much dear. Now I got the desired graph.
But one last help I need. I want to get Hurst component value against
different value of q.
So, from where I can get it?
like this  (Generalized Hurst exponents for 7 CEE stock indices and their
range over q ∈ [−10, 10].)

**Comment by stfbnc** [comment]
It is the second plot generated by `mfdfa_example.py`.

In general, the function at line 23 returns a list of the generalized Hurst exponents for each q.

**Comment by Rabia-Raja** [comment]
yes it worked.
Thanks a lot for your help.
